### ISSUE TITLE
不能直接设置背景图片吗

### ISSUE THREAD

**Issue by sheilazxx** [CB-ysx/CBRatingBar#1]

**Comment by CB-ysx** [comment]
目前只能设置svg图片中的path数据

**Comment by charlieysx** [comment]
@sheilazxx 目前只能设置svg图片中的path数据

**Comment by sheilazxx** [comment]
自己的图片svg图片中的path数据怎么获取呢

**Comment by sheilazxx** [comment]
能动态获取吗，假如图片是服务器给的

**Comment by charlieysx** [comment]
@sheilazxx 
![image](https://user-images.githubusercontent.com/12019593/32158021-d918bfd4-bd14-11e7-8933-d9fa72a2b950.png)
把你的svg图片拖进编辑器，就能看到其中的数据，把画红线的部分设置给CBRatingBar就可以。从服务器传来的图片的话，暂时没有实现，可以给你个思路，

**Comment by charlieysx** [comment]
@sheilazxx 从服务器获取的，首先要确保是svg图，然后可以写个正则匹配出里面的数据

**Comment by sheilazxx** [comment]
嗯嗯，谢谢了
