### ISSUE TITLE
希望增加一个功能

### ISSUE THREAD

**Issue by tvvbbb** [CB-ysx/CBRatingBar#4]
就是每颗星星满的方向不是从左到右，是从上到下，代码如下，但没有写set和xml的，希望楼主加上，这样通用性更强。
` private Bitmap getCoverStarBitmap(float dx) {
        //将星星绘制到star上
        Bitmap star = Bitmap.createBitmap(width, starSize, Bitmap.Config.ARGB_8888);
        Canvas starCanvas = new Canvas(star);
        drawStar(starCanvas, starFillPaint);
        //在star上填充颜色
        Bitmap finalStar = Bitmap.createBitmap(width, starSize, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(finalStar);
        canvas.save();
        //dx
        int starCount = (int)(dx/starSize);
        float remain = dx% starSize;
        canvas.clipRect(0, 0, starCount * starSize, starSize);
        canvas.clipRect(starCount * starSize + getStarSpace() * starCount,starSize,(starCount + 1) * starSize + getStarSpace() * starCount, starSize - remain);
        canvas.drawRect(0, 0, width, starSize, starCoverPaint);
        canvas.restore();
        canvas.drawBitmap(star, 0, 0, starPaint);
        return finalStar;
    }`

**Comment by charlieysx** [comment]
@tvvbbb  首先感谢您提的建议，您提供的代码我这边没效果，所以我自己重新写了
代码已更新，3.0.0版可以设置进度填充方向，有四种：
`
left_to_right
right_to_left
top_to_bottom
bottom_to_top
`

xml中使用方法：
`
app:starCoverDir="top_to_bottom"
`

java中使用方法：
`
.setCoverDir(CBRatingBar.CoverDir.topToBottom) //设置进度覆盖的方向
`

**Comment by tvvbbb** [comment]
恩，那就好，代码我是在源码上改动的，运行测试过可以，没所谓了，有更新就好
