### ISSUE TITLE
请问  defult 星星数据可以提供下吗！！

### ISSUE THREAD

**Issue by wangchengyan** [CB-ysx/CBRatingBar#5]
请问  Default  星星数据可以提供下吗！！

**Comment by charlieysx** [comment]
path数据？在这个库的string资源文件里面就有

**Comment by wangchengyan** [comment]
> path数据？在这个库的string资源文件里面就有

资源文件里面是圆角星星，我想要直角星星 ~~

**Comment by charlieysx** [comment]
@wangchengyan M511.082606 89.707115 640.347668 381.582695 957.756785 415.585113 720.110293 628.727515 785.8526 941.099918 509.716492 780.939195 232.943888 940.007027 299.926442 627.883287 63.132364 413.8107 380.657114 381.064902 511.082606 89.707115Z

**Comment by charlieysx** [comment]
@wangchengyan 推荐个网站，可以在上面找（下载纯色的svg，然后用编辑器打开拿path数据就行）：http://www.iconfont.cn/

**Comment by wangchengyan** [comment]
> @wangchengyan 推荐个网站，可以在上面找（下载纯色的svg，然后用编辑器打开拿path数据就行）：http://www.iconfont.cn/


感谢啊  爱你！！
