### ISSUE TITLE
精确的控制半颗星星

### ISSUE THREAD

**Issue by protectedMan** [CB-ysx/CBRatingBar#8]
starSpace一旦设置了starProgress对星星数量的影响就是不是固定的百分比了。如图，starProgress设置9的时候应该占用是四个半。
![image](https://user-images.githubusercontent.com/17565737/48324243-f835d700-e66a-11e8-9991-62b7228993ca.png)

**Comment by charlieysx** [comment]
@protectedMan 大概知道原因，因为设置了starSpace，而我计算的时候没有考虑到starSpace。

**Comment by charlieysx** [comment]
@protectedMan 具体可以看onDraw方法中的coverSize的计算，你可以从这里去改。

**Comment by protectedMan** [comment]
我在外部做了一个映射。。。
![image](https://user-images.githubusercontent.com/17565737/48324717-0e449700-e66d-11e8-8c24-571341411dd7.png)
