### ISSUE TITLE
你的星星的进度控制有问题,我手动改了一下

### ISSUE THREAD

**Issue by 424385117** [CB-ysx/CBRatingBar#9]
>`@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        float coverSize = 0;
        float percent = starProgress * 100 / starMaxProgress;
        for (int i = 0; i < starCount; i++) {
            if (percent > i * 100 / starCount && percent <= (i + 1) * 100 / starCount) {
                coverSize = (float) (((starSize * starCount) * starProgress * 1.0 / starMaxProgress) + starSpace * i);
                break;
            }
        }
        if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
            coverSize = (float) (starSize * starProgress * 1.0 / starMaxProgress);
        }
        //将已经填充了颜色的星星绘制到画布上
        canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
        if (showStroke) {
            //给星星添加边框
            drawStar(canvas, starStrokePaint);
        }
    }`

**Comment by 424385117** [comment]
`@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        float coverSize = 0;
        float percent = starProgress * 100 / starMaxProgress;
        for (int i = 0; i < starCount; i++) {
            if (percent > i * 100 / starCount && percent <= (i + 1) * 100 / starCount) {
                coverSize = (float) (((starSize * starCount) * starProgress * 1.0 / starMaxProgress) + starSpace * i);
                break;
            }
        }
        if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
            coverSize = (float) (starSize * starProgress * 1.0 / starMaxProgress);
        }
        //将已经填充了颜色的星星绘制到画布上
        canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
        if (showStroke) {
            //给星星添加边框
            drawStar(canvas, starStrokePaint);
        }
    }`

**Comment by charlieysx** [comment]
@424385117  利用中午休息时间思考了下，可以直接计算，不用for和if判断，代码大概如下，只用js计算测试，得到数据是正确的，因为现在做前端，没有装Android环境，没有真机测试，有兴趣可以测试提个pr

`
@override
protected void onDraw(Canvas canvas) {
    super.onDraw(canvas);

    float coverSize = 0;
    float percent = starProgress * 1.0 /  starMaxProgress

    if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
        coverSize = (float) (starSize * percent);
    } else {
        // 计算间隔数
        float spaceCount = Math.max(0, Math.floor(percent - 0.1))
        // 覆盖的星星+间隔
        coverSize = percent * startSize + spaceCount * starSpace
    }

    //将已经填充了颜色的星星绘制到画布上
    canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
    if (showStroke) {
        //给星星添加边框
        drawStar(canvas, starStrokePaint);
    }
}
`

**Comment by 424385117** [comment]
你的思路是对的,但是你的代码可能是js的代码,有点问题,我改了下
`@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        float coverSize = 0;
        float percent = starProgress * 1.0F / starMaxProgress;
        if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
            coverSize = starSize * percent;
        } else {
            // 计算间隔数
            int coverStarCount = (int) Math.floor(starCount * percent);
            // 覆盖的星星+间隔
            coverSize = percent * starSize * starCount + coverStarCount * starSpace;
        }
        //将已经填充了颜色的星星绘制到画布上
        canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
        if (showStroke) {
            //给星星添加边框
            drawStar(canvas, starStrokePaint);
        }
    }`

**Comment by 424385117** [comment]
@CB-ysx 你的思路是对的,但是你的代码有点问题,我改了下
`
@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        float coverSize = 0;
        float percent = starProgress * 1.0F / starMaxProgress;
        if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
            coverSize = starSize * percent;
        } else {
            // 计算间隔数
            int coverStarCount = (int) Math.floor(starCount * percent);
            // 覆盖的星星+间隔
            coverSize = percent * starSize * starCount + coverStarCount * starSpace;
        }
        //将已经填充了颜色的星星绘制到画布上
        canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
        if (showStroke) {
            //给星星添加边框
            drawStar(canvas, starStrokePaint);
        }
    }
`

**Comment by 424385117** [comment]
> @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        float coverSize = 0;
        float percent = starProgress * 1.0F / starMaxProgress;
        if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
            coverSize = starSize * percent;
        } else {
            // 计算间隔数
            int coverStarCount = (int) Math.floor(starCount * percent);
            // 覆盖的星星+间隔
            coverSize = percent * starSize * starCount + coverStarCount * starSpace;
        }
        //将已经填充了颜色的星星绘制到画布上
        canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
        if (showStroke) {
            //给星星添加边框
            drawStar(canvas, starStrokePaint);
        }
    }

**Comment by 424385117** [comment]
> @424385117 利用中午休息时间思考了下，可以直接计算，不用for和if判断，代码大概如下，只用js计算测试，得到数据是正确的，因为现在做前端，没有装Android环境，没有真机测试，有兴趣可以测试提个pr
> 
> `
> @override
> protected void onDraw(Canvas canvas) {
> super.onDraw(canvas);
> 
> ```
> float coverSize = 0;
> float percent = starProgress * 1.0 /  starMaxProgress
> 
> if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
>     coverSize = (float) (starSize * percent);
> } else {
>     // 计算间隔数
>     float spaceCount = Math.max(0, Math.floor(percent - 0.1))
>     // 覆盖的星星+间隔
>     coverSize = percent * startSize + spaceCount * starSpace
> }
> 
> //将已经填充了颜色的星星绘制到画布上
> canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
> if (showStroke) {
>     //给星星添加边框
>     drawStar(canvas, starStrokePaint);
> }
> ```
> }
> `

你的思路是对的,但是代码有点问题,我改了下
```
@Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        float coverSize = 0;
        float percent = starProgress * 1.0F / starMaxProgress;
        if (coverDir == CoverDir.topToBottom || coverDir == CoverDir.bottomToTop) {
            coverSize = starSize * percent;
        } else {
            // 计算间隔数
            int coverStarCount = (int) Math.floor(starCount * percent);
            // 覆盖的星星+间隔
            coverSize = percent * starSize * starCount + coverStarCount * starSpace;
        }
        //将已经填充了颜色的星星绘制到画布上
        canvas.drawBitmap(getCoverStarBitmap(coverSize), 0, 0, null);
        if (showStroke) {
            //给星星添加边框
            drawStar(canvas, starStrokePaint);
        }
    }
```

**Comment by charlieysx** [comment]
@424385117 嗯嗯，刚刚写成Android这边，忘记乘starCount了
